remote_theme: "mmistakes/minimal-mistakes@4.19.1"
title: "agfline"
subtitle: 
name: "Adrien Gesta-Fline"
description: "Ici on partage un café, on parle technique et parfois politique."
url: "https://agfline.github.io/"
#baseurl: "docs"
read_time: true

main:
  - title: "Posts"
    url: /posts/
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/


plugins:
  - jekyll-include-cache
