remote_theme: "mmistakes/minimal-mistakes@4.19.1"
title: "agfline"
subtitle: "Vive la Commune et le logiciel libre."
name: "Adrien Gesta-Fline"
description: ""
url: "https://agfline.github.io/"
repository: "agfline/agfline.github.io"
#baseurl: "docs"

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - "_pages"
  - "_posts"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
  
  
author:
  name             : "Adrien Gesta-Fline"
  avatar           : "assets/img/profile.jpg"
  bio              : "<i>\"ingénieur\" du son le jour, développeur révolutionnaire la nuit.</i>"
  location         : "France"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:dev.agfline@posteo.net
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/agfline"
    - label: "Wikipedia"
      icon: "fab fa-fw fa-wikipedia-w"
      url: "https://fr.wikipedia.org/wiki/Utilisateur:Agfline"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  #- jekyll-include-cache
