remote_theme: "mmistakes/minimal-mistakes@4.19.1"
title: "agfline"
subtitle: 
name: "Adrien Gesta-Fline"
description: "Ici on partage un café, on parle technique et parfois politique."
url: "https://agfline.github.io/"
#baseurl: "docs"

layout: single

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

plugins:
  - jekyll-include-cache
